name: PR Build

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    if: github.repository == 'zhensherlock/watermark-js-plus'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Package
        run: npm i

      - name: Build Package
        run: npm run build

      - name: Test Package
        run: npm run test

      - name: Build Docs Package
        run: npm run docs:build
